import bcrypt from "bcryptjs";
const data = {
  users: [
    {
      name: "admin",
      email: "admin@artzone.com",
      password: bcrypt.hashSync("abc123"),
      isAdmin: true,
      secLevel: 1,
    },
    {
      name: "Jane Doe",
      email: "jane@doe.com",
      password: bcrypt.hashSync("qaz123"),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "Sofa",
      slug: "sofa",
      category: "Furniture",
      image: "/images/products/sofa1.jfif",
      price: 18,
      brand: "generic",
      rating: 4.5,
      reviews: 10,
      leftinStock: 10,
      description: "A good sofa that does not make your back suffer :)",
    },
    {
      name: "Vase",
      slug: "vase",
      category: "Decoration",
      image: "/images/products/pot1.jfif",
      price: 35,
      brand: "Hand Craft",
      rating: 4.5,
      reviews: 10,
      leftinStock: 20,
      description: "A vase made with clay and love <3",
    },
    {
      name: "Drawer",
      slug: "drawer",
      category: "Furniture",
      image: "/images/products/drawer4.jfif",
      price: 9,
      brand: "generic",
      rating: 4.5,
      reviews: 10,
      leftinStock: 30,
      description:
        "A drawer that beats your laundry in a mexican standoff, because it draws quicker than anyone :)",
    },
    {
      name: "Mask",
      slug: "mask",
      category: "Decoration",
      image: "/images/products/mask3.jfif",
      price: 50,
      brand: "generic",
      rating: 4.5,
      reviews: 10,
      leftinStock: 20,
      description: "What good is the Future if the Mask is not Off the wall :)",
    },
    {
      name: "Wall Lights",
      slug: "lights",
      category: "Decoration",
      image: "/images/products/light4.jfif",
      price: 10,
      brand: "Lumos",
      rating: 4.5,
      reviews: 10,
      leftinStock: 50,
      description:
        "Let there be light and there were bulbs that made the sun and fireflies jealous ;)",
    },
    {
      name: "Wall Painting",
      slug: "painting",
      category: "Decoration",
      image: "/images/products/paint6.jfif",
      price: 1000,
      brand: "Itachi",
      rating: 5,
      reviews: 1000,
      leftinStock: 1,
      description: "Every justu is futile before these very eyes of mine :-|",
    },
    {
      name: "Plant",
      slug: "plant",
      category: "Decoration",
      image: "/images/products/plant1.jfif",
      price: 5,
      brand: "Gaya",
      rating: 4.5,
      reviews: 10,
      leftinStock: 5,
      description:
        "Plants are just as important as oxygen, if you doubt me breathe more :)",
    },
    {
      name: "Paon",
      slug: "sculpture",
      category: "Decoration",
      image: "/images/products/sculpt3.jfif",
      price: 300,
      brand: "Gaya",
      rating: 4.5,
      reviews: 10,
      leftinStock: 1,
      description: "Athena !!! :)",
    },
    {
      name: "Necklace",
      slug: "necklace",
      category: "Fashion",
      image: "/images/products/jewel2.jfif",
      price: 300,
      brand: "hand Craft",
      rating: 4.5,
      reviews: 10,
      leftinStock: 2,
      description:
        "Your neck may not wear shoes but you can give them a lace :)",
    },
  ],
};

export default data;
